### ISSUE TITLE
I can´t access with telegram

### ISSUE THREAD

**Issue by anmorfe** [asmaklad/TeleView#2] opened 2021-04-16 16:36 UTC
I have instaled the sketch properly in esp32 cam as a esp CAMERA_MODEL_AI_THINKER, no errors, i have configured the telegram token and the chat id, but the telegram bot doesn´t shows anything... Could you tell me what is the problem...?
The esp32 cam was bought in aliexpress, but the sketch didn`t show any problem...

**Comment by anmorfe** [comment] 2021-04-20 07:13
There is some kind of problem with telegram comunication...

**Comment by asmaklad** [comment] 2021-04-20 07:22
Hi anmorfe. 
Have you tried to connect the board to the Serial port and check what kind of errors it shows ?
Is the wifi connected ? 
have you tried the Arduino IDE's Sample sketch first ? 
regards ahmed

**Comment by anmorfe** [comment] 2021-04-20 07:49
Yes, Serial port doesn't shows problems, And i have tried this seketch and works properly, but it's very simple. 
https://randomnerdtutorials.com/telegram-esp32-cam-photo-arduino/

Your sketch is loaded properly via arduino ide, the board creates the access point, I can connect to my wifi but it seems that doesn't connet to telegram

**Comment by anmorfe** [comment] 2021-04-20 07:56
I have tried this one too
https://github.com/fustyles/Arduino/blob/master/ESP32-CAM_PIR_Telegram/ESP32-CAM_PIR_Telegram.ino

and via serial it shows :
"Connected to api.telegram.org failed"

**Comment by anmorfe** [comment] 2021-04-20 09:56
This is the serial monitor output:


rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:10944
load:0x40080400,len:6388
entry 0x400806b4
Compile Date:Apr 20 2021
Compile Time:11:49:20
Compile Compiler:201103

[["/start", "/options"],["/sendPhoto"],["/vflip", "/hmirror", "/setlapse", "/webCaptureOn"],["/useFlash"],["/QQVGA","/QQVGA2","/QCIF","/HQVGA","/QVGA","/CIF"],["/VGA","/SVGA","/XGA","/SXGA","/UXGA","/QXGA"],[]]
found settings prefrences.
*Attribute        | Value* 
```
Device Name      |TeleView
useFlash         |true
hMirror          |true
vFlip            |true
webCaptureOn     |true
frameSize        |13,,
adminChatIds     |1324678123
userChatIds      |0123456789
lapseTime        |60
timeZone         |Europe/Berlin
Last Photo taken |UNKNOWN 
```
populateResolutionsSelects#4
mDNS responder started
WiFi connected: 192.168.1.143
JAZZTEL_E4
RSSI:-43
WiFi MAC: B0:AD:C8:1F:9C:9C
IP address: 192.168.1.143
I am Alive!!

**Comment by anmorfe** [comment] 2021-04-20 09:57
Telegram bot doesn't respond to /start command

**Comment by asmaklad** [comment] 2021-04-20 10:11
just a guess, 
this line doesn't seem right :
 frameSize        |13,,
 
can you please adjust it in the UI ?

**Comment by asmaklad** [comment] 2021-04-20 10:13
Also check if the adminchatIds has a space or anyother hidden char . like tab or something.

**Comment by anmorfe** [comment] 2021-04-20 10:15
ok, I'm trying it

**Comment by anmorfe** [comment] 2021-04-20 10:19
it doesn't work....

I have change the frame size and the bot token, no results:

ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:10944
load:0x40080400,len:6388
entry 0x400806b4
Compile Date:Apr 20 2021
Compile Time:11:49:20
Compile Compiler:201103

[["/start", "/options"],["/sendPhoto"],["/vflip", "/hmirror", "/setlapse", "/webCaptureOn"],["/useFlash"],["/QQVGA","/QQVGA2","/QCIF","/HQVGA","/QVGA","/CIF"],["/VGA","/SVGA","/XGA","/SXGA","/UXGA","/QXGA"],[]]
found settings prefrences.
*Attribute        | Value* 
```
Device Name      |TeleView
useFlash         |true
hMirror          |true
vFlip            |true
webCaptureOn     |true
frameSize        |6,VGA,640x480
adminChatIds     |*********
userChatIds      |**********
lapseTime        |60
timeZone         |Europe/Berlin
Last Photo taken |UNKNOWN 
```
populateResolutionsSelects#4
mDNS responder started
WiFi connected: 192.168.1.143
JAZZTEL_E4
RSSI:-39
WiFi MAC: B0:AD:C8:1F:9C:9C
IP address: 192.168.1.143
I am Alive!!

**Comment by anmorfe** [comment] 2021-04-20 10:21
I think there is a problem about comunication between module and telegram bot...

**Comment by asmaklad** [comment] 2021-04-20 10:28
ok if you think the communication with Telegram is the problem:
Can you use web telegram on the same wifi network as your ESP32-CAM module ?
does this link work  https://web.telegram.org/  on your pc ?

**Comment by asmaklad** [comment] 2021-04-20 10:29
are you using any proxy ? or middle entities in your wifi lke pi-hole or something ?

**Comment by asmaklad** [comment] 2021-04-20 10:30
double check the bot token

**Comment by asmaklad** [comment] 2021-04-20 10:32
in the file  TeleView/UniversalTelegramBot.h  , change line 92 to bool _debug = true;
if you have problems with Telegram , then you should see it as in UniversalTelegramBot.cpp lines 57 to 62

**Comment by anmorfe** [comment] 2021-04-20 10:38
> ok if you think the communication with Telegram is the problem:
> Can you use web telegram on the same wifi network as your ESP32-CAM module ?
> does this link work https://web.telegram.org/ on your pc ?

I'm using  web telegram on the same wifi network
Yes, Telegram web works properly

**Comment by anmorfe** [comment] 2021-04-20 10:39
> are you using any proxy ? or middle entities in your wifi lke pi-hole or something ?

no proxies

**Comment by anmorfe** [comment] 2021-04-20 10:44
after change debug option, serial monitor shows:

```
populateResolutionsSelects#4
mDNS responder started
WiFi connected: 192.168.1.143
JAZZTEL_E4
RSSI:-35
WiFi MAC: B0:AD:C8:1F:9C:9C
IP address: 192.168.1.143
SEND Post Message
[BOT Client]Connecting to server
[BOT Client]Conection error

[BOT Client]Connecting to server
[BOT Client]Conection error

[BOT Client]Connecting to server
[BOT Client]Conection error

[BOT Client]Connecting to server
[BOT Client]Conection error

[BOT Client]Connecting to server
[BOT Client]Conection error

[BOT Client]Connecting to server
[BOT Client]Conection error

[BOT Client]Connecting to server
[BOT Client]Conection error

**Comment by anmorfe** [comment] 2021-04-20 10:48
I am Alive!!
GET Update Messages
[BOT]Connecting to server
[BOT]Conection error
Received empty string in response!
GET Update Messages
[BOT]Connecting to server
[BOT]Conection error
Received empty string in response!
GET Update Messages
[BOT]Connecting to server
[BOT]Conection error
Received empty string in response!
GET Update Messages
[BOT]Connecting to server
[BOT]Conection error
Received empty string in response!
GET Update Messages

**Comment by anmorfe** [comment] 2021-04-20 11:06
![captura](https://user-images.githubusercontent.com/82670670/115386072-3db24300-a1d9-11eb-9389-43ef5fdf9fb8.jpg)

**Comment by anmorfe** [comment] 2021-04-20 11:20
I have tried using my phon as an access point... Same result:
GET Update Messages
[BOT]Connecting to server
[BOT]Conection error
Received empty string in response!

**Comment by asmaklad** [comment] 2021-04-20 12:44
then can you please double check the bot token or even create a new one

**Comment by anmorfe** [comment] 2021-04-20 13:37
I have revoke the token, even create a new one. No results.

**Comment by asmaklad** [comment] 2021-04-20 14:31
let me sleep on it .. I will think about it.

**Comment by anmorfe** [comment] 2021-04-20 17:38
Ok. I'm very grateful for your interest. I think your code is amazing... if I'm able to make it works... ;). I'm trying to make a cheap security system for my second house. We live there only few days every month, and this sektch seems to be all that I'm looking for.

I have found another programs but no one like yours.

**Comment by asmaklad** [comment] 2021-04-22 01:43
Ok , I think I got to the bottom of this.
I have a running board that is perfectly working fine. when I try to upload the code to a new board , I get similar errors. 
it is partially fixed when I add the "botClient.setInsecure()" and the board can send and receive messages, but it fails in sending photos ! again error with the ssl_client.cpp:301 with some sort of UNKNOWN ERROR..
It seems there is a bug in the current ESP32 library version 1.0.6 
Please follow these instructions to downgrade the version of the ESP32 Board Libraries:
1)  in the menu "Tools" -> Board (xyz) -> Board Manager
2) in the search box type "ESP32"
3) got to the "select version" checkbox and select  the version "1.0.4"
4) recompile and upload
please test and feed me back so I can update the README file.

**Comment by anmorfe** [comment] 2021-04-22 07:57
Have a good day;

I have been trying to change the telegram_utils.h by adding "botClient.setInsecure()" and this is the result:
![image](https://user-images.githubusercontent.com/82670670/115676047-7f64fa00-a34f-11eb-8962-fe7c0a0a7e03.png)

However, I have noticed that if I downgrade the ESP32 library to 1.0.4, the code works perfectly without adding this line "botClient.setInsecure()" BUT.....it seems that the SSID and the password aren't saved properly  when they are grabbed in web page AutoConnect... I mean, firstly i load the sketch to the board, the board creates an access point named Teleview, then I connect my phone to this ap and I can configure all the parameters (SSID and password), but when I restart ther board or unplug and plug  the power cord, I notice that SSID and password weren't saved properly....

**Comment by anmorfe** [comment] 2021-04-22 08:24
About using a pir, i have added to the camera_pins.h a line like that
#define PIR_PIN  13
But when a lode the code with this change it detect movement and sen photos continuously....

**Comment by asmaklad** [comment] 2021-04-22 08:33
Losing the SSID credentials is not a normal behavior.
I am just guessing here , please try these:
1) I have AutoConnect Library version 1.1.3 and ArduinoJson Library version 5.13.5 can you please align to these versions ?
2) I sometimes have similar behavior , but I think after several reboots or using the reset button , it works.

to stop motion detection you have to set it to false from the Telegram Keyboard or type "/motDetectOn" case sensitive  .
if you can't see the Telegram keyboard , then type "/start" or "/options" and then you can just click the button you want.
![image](https://user-images.githubusercontent.com/753939/115682881-2d73a280-a356-11eb-9db7-b883e07c85a4.png)


as for the #define BUTTON_PIN 34  it is not needed. The code doesn't use it currently. but I just put there to in case I decide to use it in the future.

**Comment by asmaklad** [comment] 2021-04-22 08:41
Try also to setup the ArduinoIDE as Follows in the Tools menue:
![image](https://user-images.githubusercontent.com/753939/115684039-4d579600-a357-11eb-9117-399171f20a47.png)

**Comment by anmorfe** [comment] 2021-04-22 08:42
I don't know if I explained well, when I configure the pin 13 to receive the signal from pir, the telegram bot send every few seconds "motion detection" and send an image, even there is no movement.

**Comment by anmorfe** [comment] 2021-04-22 08:42
> Try also to setup the ArduinoIDE as Follows in the Tools menue:
> ![image](https://user-images.githubusercontent.com/753939/115684039-4d579600-a357-11eb-9117-399171f20a47.png)

ok

**Comment by asmaklad** [comment] 2021-04-22 08:44
> I don't know if I explained well, when I configure the pin 13 to receive the signal from pir, the telegram bot send every few seconds "motion detection" and send an image, even there is no movement.

have you added a pull up or pull down resistor to the PIR ?

**Comment by anmorfe** [comment] 2021-04-22 08:46
> > I don't know if I explained well, when I configure the pin 13 to receive the signal from pir, the telegram bot send every few seconds "motion detection" and send an image, even there is no movement.
> 
> have you added a pull up or pull down resistor to the PIR ?

no...

**Comment by asmaklad** [comment] 2021-04-22 08:55
I understand you use the Board "AI Thinker ESP32-CAM"
according to this : https://randomnerdtutorials.com/esp32-cam-pir-motion-detector-photo-capture/  you need a power down or up resistor ( I don't know how to identify it)
![image](https://user-images.githubusercontent.com/753939/115686163-37e36b80-a359-11eb-92c7-e6cddd05d477.png)

**Comment by anmorfe** [comment] 2021-04-22 08:58
> I understand you use the Board "AI Thinker ESP32-CAM"
> according to this : https://randomnerdtutorials.com/esp32-cam-pir-motion-detector-photo-capture/ you need a power down or up resistor ( I don't know how to identify it)
> ![image](https://user-images.githubusercontent.com/753939/115686163-37e36b80-a359-11eb-92c7-e6cddd05d477.png)

Ok

**Comment by asmaklad** [comment] 2021-04-22 09:01
is the SSID problem resolved yet ?

**Comment by anmorfe** [comment] 2021-04-22 09:04
> > Try also to setup the ArduinoIDE as Follows in the Tools menue:
> > ![image](https://user-images.githubusercontent.com/753939/115684039-4d579600-a357-11eb-9117-399171f20a47.png)
> 
> ok

This configuration works but same results with wifi credentials

**Comment by anmorfe** [comment] 2021-04-22 09:05
could i use pinMode(PIN_PIR, INPUT_PULLUP);   ???

**Comment by asmaklad** [comment] 2021-04-22 09:08
for the PIR issue, some one asked the same questions last year and I see I gave him a similar answer:
https://github.com/asmaklad/TeleView/issues/1 
It should be a PULL_DOWN 
Try this maybe it works with softwear only:
in TeleView.ino, change the line 230 "pinMode(PIR_PIN, INPUT); " to 
pinMode(PIR_PIN, INPUT_PULLDOWN  );
Who knows , maybe we learn something new today.

**Comment by asmaklad** [comment] 2021-04-22 09:41
I don't know why the AutoConnect Lib it doesn't save the SSID 
if the SSID issue is still persistent, then try the following:
we need basicly to program that SSID, pass in the ESP32 rom . it keeps record of the last 10 connected WIFI.
so we need to establish the connection once and then it should remember it on its own.
got to the menu "File"-> "Examples" -> "WebServer" -> "HelloServer"

change the  line to hardcode your wifi:
const char* ssid = "........";
const char* password = "........";

then compile and upload HelloServer to your board,

then compile and upload Teleview sketch again.

**Comment by anmorfe** [comment] 2021-04-22 10:08
> for the PIR issue, some one asked the same questions last year and I see I gave him a similar answer:
> #1
> It should be a PULL_DOWN
> Try this maybe it works with softwear only:
> in TeleView.ino, change the line 230 "pinMode(PIR_PIN, INPUT); " to
> pinMode(PIR_PIN, INPUT_PULLDOWN );
> Who knows , maybe we learn something new today.

PULLDOWN isn't reognized, only pullup.....what a pitty
![image](https://user-images.githubusercontent.com/82670670/115696840-52badd80-a363-11eb-8c95-ca5a6c1d68c8.png)



![image](https://user-images.githubusercontent.com/82670670/115696909-62d2bd00-a363-11eb-9954-d69d7161e2a3.png)

**Comment by asmaklad** [comment] 2021-04-22 11:53
sorry about that. that is why you will have to do circuit I sent earlier.

or you could use this board : https://www.aliexpress.com/item/32995230085.html?spm=a2g0o.productlist.0.0.24e61f80B4job9&algo_pvid=14f6b00e-d76c-4ba6-bebf-42587f9bffdb&algo_expid=14f6b00e-d76c-4ba6-bebf-42587f9bffdb-0&btsid=0b0a556d16190923870365488eec94&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

**Comment by asmaklad** [comment] 2021-04-22 12:02
Wait a sec... It compiles with PULLDOWN ... forget about ArduinoIDE's syntax highlight ..

**Comment by anmorfe** [comment] 2021-04-22 14:10
I have tried it. It doesn't work

**Comment by asmaklad** [comment] 2021-04-22 16:35
question,. you sensor sends 1(HIGH) when detecting motion or 0 (LOW) ?
if it sends 1 all the time then you need to make pullup and only detect the LOW state :
THEN-> PINMODE = INPUT_PULLUP and line TeleView.ino:238 should have "!digitalRead(PIR_PIN)"

if it sends 0 all the time then you need to make PULLDOWN and only detect the HIGH state : (current state of the code)
THEN-> PINMODE = INPUT_DOWN and line TeleView.ino:238 should have "digitalRead(PIR_PIN)"

**Comment by anmorfe** [comment] 2021-04-22 17:48
I think I will buy TTGO, it's not expensive and 

> question,. you sensor sends 1(HIGH) when detecting motion or 0 (LOW) ?
> if it sends 1 all the time then you need to make pullup and only detect the LOW state :
> THEN-> PINMODE = INPUT_PULLUP and line TeleView.ino:238 should have "!digitalRead(PIR_PIN)"
> 
> if it sends 0 all the time then you need to make PULLDOWN and only detect the HIGH state : (current state of the code)
> THEN-> PINMODE = INPUT_DOWN and line TeleView.ino:238 should have "digitalRead(PIR_PIN)"

I have tried PULLUP and "!digitalRead(PIR_PIN)", no results. 
Same problem with WiFi credentials. Curiously, if I use ArduinoJson 1.0.6 it saves the credentials...

**Comment by asmaklad** [comment] 2021-04-23 04:11
ok just to keep track and document this later in the README :

Problem  Description |   Solution
----------------------- |  -----------
Unable to connect to Telegram |  downgrade ESP32 library to version 1.0.4
SSID credentials not saved | downgrade Arduino JSON to ArduinoJson 1.0.6

**Comment by anmorfe** [comment] 2021-04-23 10:59
I can`t understand why this code works https://github.com/fustyles/Arduino/blob/master/ESP32-CAM_PIR_Telegram/ESP32-CAM_PIR_Telegram.ino , and your code doesn't work....
I have a HC-SR501, always low unless it detects movement. In the other code, the author use INPUT_PULLUP:
![image](https://user-images.githubusercontent.com/82670670/115861920-bca2b800-a433-11eb-9a85-705b468e099f.png)

**Comment by asmaklad** [comment] 2021-04-23 14:00
me neither.
try this in https://github.com/asmaklad/TeleView/blob/master/TeleView.ino 

# in setup() line 229
#if defined(PIR_PIN)
  pinMode(PIR_PIN, INPUT_PULLUP) ; // the logical thing to work is INPUT_PULLDOWN .. but who knows !
#endif


# in loop() line 237
#if defined(PIR_PIN)
   int vPIR = digitalRead(pinPIR);
  Serial.print("PIR VALUE:");
  Serial.println(vPIR );
  if ( configItems.motDetectOn && vPIR==HIGH )) {
    Serial.println("Motion Detected."); 
    bot.sendMessage(configItems.adminChatIds, "Motion Detected!","" );
    String restult= sendCapturedImage2Telegram(configItems.adminChatIds);
    Serial.println("restult: "+restult);
    delay(100);
  }  
#endif

**Comment by anmorfe** [comment] 2021-04-23 17:51
INCREDIBLE!!!! It works.....  I can believe it.... Thank you for your patient.... Now I ony have the problem with wifi credentials...

**Comment by asmaklad** [comment] 2021-04-23 21:05
ok gr8.
now try this  : 
uncomment line 166 in TeleView.ino
acConfig.autoSave=AUTOCONNECT_USE_PREFERENCES;

**Comment by anmorfe** [comment] 2021-04-24 06:53
It shows an error:

![image](https://user-images.githubusercontent.com/82670670/115950277-8ec47e80-a4da-11eb-96f4-67b08e1f73ea.png)

**Comment by asmaklad** [comment] 2021-04-25 00:46
I have made  some heavy updates  in the project this weekend. 
I would appreciate if you test them before I release them.
you can download them from here : 
https://github.com/asmaklad/TeleView/tree/feature/upgrade_telegram_library

Please keep your current code and don't overwrite it just yet.

**Comment by anmorfe** [comment] 2021-04-26 10:21
Ok, I have tried your code without pir sensor. I have used the libraries as you said in the read me file and it works perfectly... No errors. No problem with WiFi credentials. 
Now, I'm going to try it with modifications in order to use an external pir sensor. 
I will share the results. Thanks again.

**Comment by asmaklad** [comment] 2021-04-26 10:58
Great I am delighted that it works.I will merge the code.On Apr 26, 2021 12:22, anmorfe ***@***.***> wrote:
Ok, I have tried your code without pir sensor. I have used the libraries as you said in the read me file and it works perfectly... No errors. No problem with WiFi credentials.
Now, I'm going to try it with modifications in order to use an external pir sensor.
I will share the results. Thanks again.

**Comment by anmorfe** [comment] 2021-04-26 12:03
I have tried using pir sensor, I only have add "#define PIR_PIN 13" in camera_pins.h, no more changes and it works better than before (sometimes it trigger whithout real motion near the sensor)...
I'm very gratefull with your help.
If I'm allowed to abuse your patience, I would like you to give me an advice about how to modify your code in order to add an output pin connected to a buzzer that make an alarm sound when movement is detected. It wold be nice to add a button wich turn on or turn off the alarm sound....
I remind you that the objective is to have a security surveillance system...

**Comment by asmaklad** [comment] 2021-04-26 12:32
Great .
Sure no problem. but I need some more input first:
1) What type of a buzzer ? 
2) Which PIN you connect it to ?
3) Sample triggering code if possible.

You could add a physical switch in series with the buzzer to enable/disable it. (no software mods required)

**Comment by anmorfe** [comment] 2021-04-26 12:39
1.- piezo buzzer
2.- which one did you recommend?
3.- Ufff... every time the sensor detects movement?


I think I have explained myself wrong.
I meant to add a button on the telegram keyboard

**Comment by anmorfe** [comment] 2021-04-26 12:44
Something more, i have noticed tha the user doesn't work properly

![image](https://user-images.githubusercontent.com/82670670/116084305-eeb75280-a69d-11eb-97b3-2da38b36bd86.png)

**Comment by asmaklad** [comment] 2021-04-26 14:00
> Something more, i have noticed tha the user doesn't work properly
> 
> ![Sin título](https://user-images.githubusercontent.com/82670670/116084787-6e452180-a69e-11eb-82d0-515bf5221be3.png)

I think this output is not from Teleview, I think it is from another project.

**Comment by asmaklad** [comment] 2021-04-26 14:20
Ok you should use an "Active Buzzer" as per this link https://diyi0t.com/active-passive-buzzer-arduino-esp8266-esp32/
I assume PIN 12
I have not tested this code yet on a board. 
adding a button in the Telegram is such a hassle , there is so much to modify to save the configuration and display it in the Web and Telegram /options.  try to make physical easier.
I have made some mods for the Buzzer in this branch:
https://github.com/asmaklad/TeleView/tree/feature/add_buzzer

**Comment by asmaklad** [comment] 2021-04-26 17:20
Userchatid doesnt work. Not implemented yet.
It is in the readme.

**Comment by anmorfe** [comment] 2021-04-26 18:04
> Userchatid doesnt work. Not implemented yet.
> It is in the readme.

Sorry, I didn't read it...

**Comment by asmaklad** [comment] 2021-04-27 16:46
ok now the user ID works.
also it is possible to add the bot into a group and there you can have as many people as you want controlling it.
please  check this branch: https://github.com/asmaklad/TeleView/tree/feature/add_buzzer

**Comment by anmorfe** [comment] 2021-04-27 17:30
Thanks a lot... I will test it...
 I have been trying the code, and I have noticed that after five or six hours more or less, the system freezes. 
Do you know what the reason could be? I have add a heatsink to the processor, but the problem persist...

**Comment by asmaklad** [comment] 2021-04-28 06:35
It is very difficult to troubleshoot those issues remotely .  However, I would try the following:
1) Disconnect the PIR sensor . (just to find out the root cause)
2) Connect the ESP to a serial port and record the error that it reports in the Serial monitor.
3) Some Internet chatter suggest changing the power supply/micro USB cable used with the ESP.
4) disable web-monitoring ? Are you using it frequently ? like open it in a browser and auto refresh every couple of seconds. (don't do that)
5) Try reducing the CPU frequency from the tools menu.
 
In any case : These devices needs to have a watchdog circuit installed around it that reboots it every time it stalls. A good solution is to get one of those IKEA time switches that reboots the device every couple of hours:
https://www.ikea.com/gb/en/p/taenda-timer-24-hours-indoor-earthed-white-10445765/

**Comment by asmaklad** [comment] 2021-04-28 06:40
One more thing to try:
in telegram_utils.h , double this number : 
int Bot_mtbs = 1000; //mean time between scan messages
this will slow the telegram response.

**Comment by asmaklad** [comment] 2021-04-28 16:07
I made more changes , now more elegant interface.

**Comment by anmorfe** [comment] 2021-04-28 17:41
I´m going to test it....

**Comment by asmaklad** [comment] 2021-05-03 17:48
Check the latest changes  in the master branch. I added also the Buzzer button you asked for and many more. 

I am closing this Issue.

**Comment by asmaklad** [comment] 2021-05-03 17:48
done

**Closed** 2021-05-03 17:48 UTC
